// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class UseraccountTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void userregistration() {
    driver.get("https://www.beta.drive-now.com/en");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.id("country-home")).click();
    driver.findElement(By.linkText("Berlin")).click();
    js.executeScript("window.scrollTo(0,1.600000023841858)");
    {
      WebElement element = driver.findElement(By.cssSelector(".button-wrapper span"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".button-wrapper span")).click();
    vars.put("email", js.executeScript("return 'annkk57+' + Math.floor(Math.random() * 100) + '@gmail.com'"));
    driver.findElement(By.cssSelector("#email-container > .no-wrap-clip")).click();
    driver.findElement(By.id("loginDetails.email")).sendKeys(vars.get("email").toString());
    driver.findElement(By.cssSelector("#password-container > .no-wrap-clip")).click();
    driver.findElement(By.id("loginDetails.password")).sendKeys("yasy3902");
    driver.findElement(By.cssSelector(".show-password > img")).click();
    driver.findElement(By.id("loginDetails.securityQuestion")).click();
    driver.findElement(By.id("loginDetails.securityAnswer")).sendKeys("123");
    driver.findElement(By.id("loginDetails.securityQuestion")).click();
    {
      WebElement dropdown = driver.findElement(By.id("loginDetails.securityQuestion"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+What is your mother's maiden name\?']")).click();
    }
    driver.findElement(By.id("loginDetails.securityQuestion")).click();
    driver.findElement(By.cssSelector(".button")).click();
    vars.put("name", js.executeScript("return 'annkk57+' + Math.floor(Math.random() * 100)"));
    driver.findElement(By.cssSelector("span:nth-child(3) > label")).click();
    driver.findElement(By.cssSelector("#firstName-container > .no-wrap-clip")).click();
    driver.findElement(By.id("primaryDetails.lastName")).sendKeys("uhh");
    {
      WebElement element = driver.findElement(By.id("primaryDetails.street"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    driver.findElement(By.id("primaryDetails.street")).click();
    driver.findElement(By.id("primaryDetails.street")).sendKeys("ygvvv");
    {
      WebElement element = driver.findElement(By.cssSelector("#streetAddition-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    driver.findElement(By.cssSelector("#streetAddition-container > .no-wrap-clip")).click();
    {
      WebElement element = driver.findElement(By.id("primaryDetails.streetNumber"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.streetNumber"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.streetNumber"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("primaryDetails.streetNumber")).click();
    driver.findElement(By.id("primaryDetails.streetNumber")).sendKeys("55");
    driver.findElement(By.id("primaryDetails.streetNumber")).sendKeys("55");
    driver.findElement(By.id("primaryDetails.firstName")).sendKeys(vars.get("name").toString());
    {
      WebElement element = driver.findElement(By.id("primaryDetails.areaCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.areaCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.areaCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("primaryDetails.areaCode")).click();
    driver.findElement(By.id("primaryDetails.areaCode")).sendKeys("01067");
    driver.findElement(By.id("primaryDetails.areaCode")).sendKeys("01067");
    driver.findElement(By.id("primaryDetails.areaCode")).sendKeys("01067");
    {
      WebElement element = driver.findElement(By.cssSelector("#city-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#city-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#city-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#city-container > .no-wrap-clip")).click();
    driver.findElement(By.id("primaryDetails.city")).sendKeys("Brlin");
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-number"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-number"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-number"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-number")).click();
    driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-number")).sendKeys("0638559088");
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-country-code"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-country-code"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-country-code"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-country-code")).click();
    driver.findElement(By.id("primaryDetails.primaryDetails.mobileNumber-country-code")).sendKeys("+380");
    driver.findElement(By.id("preferredCity-container")).click();
    driver.findElement(By.id("primaryDetails.preferredCity")).click();
    {
      WebElement dropdown = driver.findElement(By.id("primaryDetails.preferredCity"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+Berlin']")).click();
    }
    driver.findElement(By.id("primaryDetails.preferredCity")).click();
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("dateOfBirth-container")).click();
    driver.findElement(By.id("dateOfBirth-day")).click();
    driver.findElement(By.id("dateOfBirth-month")).click();
    {
      WebElement dropdown = driver.findElement(By.id("dateOfBirth-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+11']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("dateOfBirth-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+11']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("dateOfBirth-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+11']")).click();
    }
    driver.findElement(By.id("dateOfBirth-month")).click();
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("dateOfBirth-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("dateOfBirth-year")).click();
    {
      WebElement dropdown = driver.findElement(By.id("dateOfBirth-year"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+1989']")).click();
    }
    driver.findElement(By.id("dateOfBirth-day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("dateOfBirth-day"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+20']")).click();
    }
    driver.findElement(By.id("dateOfBirth-day")).click();
    driver.findElement(By.id("dateOfBirth-year")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".button")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("#number-container > .no-wrap-clip")).click();
    driver.findElement(By.id("drivingLicence.number")).sendKeys("76668i99");
    driver.findElement(By.id("drivingLicence.number")).sendKeys("76668i99");
    {
      WebElement element = driver.findElement(By.id("validFrom-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validFrom-day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-day"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+17']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-day"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+17']")).click();
    }
    driver.findElement(By.id("validFrom-day")).click();
    {
      WebElement element = driver.findElement(By.id("validFrom-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validFrom-month")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+10']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+10']")).click();
    }
    driver.findElement(By.id("validFrom-month")).click();
    {
      WebElement element = driver.findElement(By.id("validFrom-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validFrom-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validFrom-year")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-year"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+2004']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validFrom-year"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+2004']")).click();
    }
    driver.findElement(By.id("validFrom-year")).click();
    {
      WebElement element = driver.findElement(By.id("validTo-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-day"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validTo-day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validTo-day"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+16']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validTo-day"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+16']")).click();
    }
    driver.findElement(By.id("validTo-day")).click();
    {
      WebElement element = driver.findElement(By.id("validTo-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-month"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validTo-month")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validTo-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+9']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validTo-month"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+9']")).click();
    }
    driver.findElement(By.id("validTo-month")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#pin-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#pin-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#pin-container > .no-wrap-clip"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#pin-container > .no-wrap-clip")).click();
    driver.findElement(By.id("drivingLicence.pin")).sendKeys("1603");
    driver.findElement(By.id("drivingLicence.pin")).sendKeys("1603");
    {
      WebElement element = driver.findElement(By.id("validTo-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("validTo-year"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("validTo-year")).click();
    {
      WebElement dropdown = driver.findElement(By.id("validTo-year"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+2022']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("validTo-year"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:\s+2022']")).click();
    }
    driver.findElement(By.id("validTo-year")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".button")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.id("cardNumber")).sendKeys("5200 0000 0000 0007");
    driver.findElement(By.id("cardNumber")).sendKeys("5200 0000 0000 0007");
    {
      WebElement element = driver.findElement(By.id("cardMonth"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("cardMonth"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("cardMonth"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("cardMonth")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cardMonth"));
      dropdown.findElement(By.xpath("//option[. = '12']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("cardMonth"));
      dropdown.findElement(By.xpath("//option[. = '12']")).click();
    }
    driver.findElement(By.id("cardMonth")).click();
    {
      WebElement element = driver.findElement(By.id("cardYear"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("cardYear"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("cardYear"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("cardYear")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cardYear"));
      dropdown.findElement(By.xpath("//option[. = '2023']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("cardYear"));
      dropdown.findElement(By.xpath("//option[. = '2023']")).click();
    }
    driver.findElement(By.id("cardYear")).click();
    {
      WebElement element = driver.findElement(By.id("cvcCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("cvcCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("cvcCode"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("cvcCode")).click();
    driver.findElement(By.id("cvcCode")).sendKeys("123");
    driver.findElement(By.id("cvcCode")).sendKeys("123");
    driver.switchTo().defaultContent();
    {
      WebElement element = driver.findElement(By.cssSelector(".psp-send"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".psp-send"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".psp-send"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".psp-send")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".content > div"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".content > div"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".content > div"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".content > div")).click();
    {
      WebElement element = driver.findElement(By.id("registrationDetails"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("registrationDetails"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("registrationDetails"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("registrationDetails")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#approveTos-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#approveTos-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#approveTos-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#approveTos-container > .label-wrapper")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#partnersNewsletter-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#partnersNewsletter-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#partnersNewsletter-container > .label-wrapper"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#partnersNewsletter-container > .label-wrapper")).click();
    driver.findElement(By.cssSelector(".blue")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".blue"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".wrapper > .logo-wrapper > img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".wrapper > .logo-wrapper > img"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("svg > g > g > g > path"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("svg > g > g > g > path"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("svg > g > g > g > path"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("svg > g > g > g > path")).click();
    driver.findElement(By.id("login.password")).sendKeys("Yasy3902");
    driver.findElement(By.id("login.email")).sendKeys(vars.get("email").toString());
    driver.findElement(By.cssSelector(".btn-flex")).click();
    driver.findElement(By.cssSelector("#login-opener > .btn-inside")).click();
    driver.findElement(By.cssSelector(".personalized > .btn")).click();
  }
  @Test
  public void userlogin() {
    driver.get("https://www.beta.drive-now.com/hu");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.cssSelector(".text > span")).click();
    driver.findElement(By.id("login.email")).sendKeys("annkk57@gmail.com");
    driver.findElement(By.id("login.password")).sendKeys("Yasy3902");
    driver.findElement(By.cssSelector(".btn-flex")).click();
  }
}
