// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class UserbuyproductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void userbuySavingPackage() {
    driver.get("https://www.beta.drive-now.com/en");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".text > span")).click();
    driver.findElement(By.id("login.email")).sendKeys("annkk57+12@gmail.com");
    driver.findElement(By.id("login.password")).sendKeys("Yasy3902");
    driver.findElement(By.cssSelector(".btn-flex")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) .text")).click();
    driver.findElement(By.cssSelector(".package-item:nth-child(1) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".package-item:nth-child(3) .btn"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".linking-footnote")).click();
    driver.findElement(By.cssSelector(".btn-form-submit")).click();
    driver.findElement(By.cssSelector(".link > span")).click();
    driver.findElement(By.cssSelector("#login-opener > .btn-inside")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#login-opener > .btn-inside"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-black")).click();
    driver.close();
  }
  @Test
  public void userbuyVoucher() {
    driver.get("https://www.beta.drive-now.com/hu");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector("#login-opener > .btn-inside"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".icon-profile > svg"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#login-opener > .btn-inside")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".icon-profile > svg"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("login.email")).sendKeys("annkk57@gmail.com");
    driver.findElement(By.id("login.password")).sendKeys("Yasy3902");
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-flex")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) .text")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) > .tab-nav-inner")).click();
    driver.findElement(By.cssSelector(".package-item:nth-child(3) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".package-item:nth-child(3) .btn"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-form-submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-form-submit"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".icon-draw-line svg")).click();
    driver.findElement(By.cssSelector(".btn-inside > div > span")).click();
    driver.findElement(By.cssSelector(".close-icon")).click();
    driver.findElement(By.cssSelector(".icon-profile > svg")).click();
    driver.findElement(By.cssSelector(".icon-profile > svg")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
